openapi: 3.0.0
info:
  title: API Antigüedades Sthandier
  version: 1.0.0
  description: >
    Esta API permite gestionar productos antiguos del emprendimiento Antigüedades Sthandier,
    incluyendo funciones para crear, listar, actualizar, reservar y eliminar productos.

servers:
  - url: http://localhost:8888/antiguedades-backend

paths:
  /productos:
    get:
      summary: Obtener todos los productos
      responses:
        "200":
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Producto"

    post:
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductoInput"
      responses:
        "201":
          description: Producto creado exitosamente
        "400":
          description: Error de entrada

  /productos/{id}:
    get:
      summary: Obtener un producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producto"
        "404":
          description: Producto no encontrado

    put:
      summary: Actualizar un producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductoInput"
      responses:
        "200":
          description: Producto actualizado
        "404":
          description: Producto no encontrado

    delete:
      summary: Eliminar un producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Producto eliminado
        "404":
          description: Producto no encontrado

  /productos/{id}/reservar:
    patch:
      summary: Cambiar estado de reserva del producto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                estado_reserva:
                  type: string
                  enum: [disponible, reservado]
      responses:
        "200":
          description: Estado de reserva actualizado
        "400":
          description: Datos inválidos
        "404":
          description: Producto no encontrado

components:
  schemas:
    Producto:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        descripcion:
          type: string
        precio:
          type: number
          format: float
        categoria:
          type: string
        estado_reserva:
          type: string
          enum: [disponible, reservado]

    ProductoInput:
      type: object
      required:
        - nombre
        - descripcion
        - precio
        - categoria
        - estado_reserva
      properties:
        nombre:
          type: string
        descripcion:
          type: string
        precio:
          type: number
        categoria:
          type: string
        estado_reserva:
          type: string
          enum: [disponible, reservado]

x-performance:
  rateLimit: 100 requests/minute
  cacheStrategy: none
  expectedResponseTimeMs: 500
